### ISSUE TITLE
Best way to "override" the visualCaptcha in integration testing ?

### ISSUE THREAD

**Issue by fabm22** [bdotzour/visualCaptcha-java#6]
What would be the best way / advised way (if any) by visualCaptcha to circumvent the captcha validation (like always giving the same answer or something) when testing via an automated process in integration (which is the precise reason why people use captchas : to avoid automatization to be able to pass through)

Thanks

**Comment by lgarofalo** [comment]
an option count of 1, or a configuration on backend for testing to ignore captcha guess?

**Comment by carstenosu** [comment]
@fabm22 I accomplished this in our integration test environment by an approach very much like what @lelandg559 suggested. Here is a snippet from my spring-boot application that is using visualCaptcha:

`if ( captchaConfig.ignore() && !env.acceptsProfiles( Constants.SPRING_PROFILE_PRODUCTION )) {`
`return new ResponseEntity<Boolean>( Boolean.TRUE, HttpStatus.OK );`
`}`

The captchaConfig.ignore property is only set to true in our integration environment and I added the SPRING_PROFILE_PRODUCTION profile check just in case it ever gets set by mistake in prod.

**Comment by fabm22** [comment]
Thanks, yep went with that way. Thanks for help, closing.
